### ISSUE TITLE
Process dataset

### ISSUE THREAD

**Issue by ShijianXu** [yihuacheng/GazeTR#3]
Hi, thank you for your work.
I am trying to use your code but I encountered some problems.
The code/link you provided for preprocessing the dataset is not complete. More specifically, the codes provided here: [http://phi-ai.buaa.edu.cn/Gazehub/2D-dataset/](http://phi-ai.buaa.edu.cn/Gazehub/2D-dataset/) is not complete. It lacks some modules, like `gtools`, which is needed in the `data_processing_mpii.py`. I suppose the `gtools` is not a standard python lib, but a file you wrote. I tried to search for the `gtools` lib on the internet, and installed one, but it doesn't work.

Can you provide the complete code for data processing. Or maybe would it be possible that you directly release your processed datasets?

Thank you and best regards.

**Comment by yihuacheng** [comment]
I have update the gtools.py in this repository. You can directly use it. 
If you have other problems, you can contact me with email. I usually do not check the Issues.
