### ISSUE TITLE
Question about MPII data processing

### ISSUE THREAD

**Issue by ShijianXu** [yihuacheng/GazeTR#6]
Hi,

I have some problems about the MPII dataset processing and the use of MPII data in the GazeTR model.

In GazeTR `reader.py`, you define the decode function for MPII like this:
```python
def Decode_MPII(line):
    anno = edict()
    anno.face, anno.lefteye, anno.righteye = line[0], line[1], line[2]
    anno.name = line[3]

    anno.gaze3d, anno.head3d = line[5], line[6]
    anno.gaze2d, anno.head2d = line[7], line[8]
    return anno
```

And in the `data_processing_mpii.py` file you provided, you process and write the annotations into the format like this:
```python
outfile.write("Face Left Right Grid Origin whicheye 2DPoint HeadRot HeadTrans ratio FaceCorner LeftEyeCorner RightEyeCorner\n")
```
If you indeed used the same code to process the MPII dataset for training the GazeTR model, then this is not right.
You can see that `anno.gaze2d = line[7]` which is actaully corresponding to `HeadRot`.

Could you please give some explanation about how to correctly use the data_processing code and how to load the data in GazeTR?

Thank you very much and best regards

**Comment by EmilVardar** [comment]
Hi @ShijianXu!

I agree with you. It feels like the data processing is different. Did you manage to solve the issue. I am also trying to do the same rn. So it would be very helpful if you explained how you did.

Thank you.

**Comment by ShijianXu** [comment]
Sorry for late reply. It's been a long time, and I do not remember it now. I remember I contacted the original authors by email, and they responded me with some instructions. They said they do not frequently answer questions on the github, so you'd better contact them by email.

Hope it will help you.
Best regards.

**Comment by EmilVardar** [comment]
No worries! Thank you very much for the answer.

Best regards

**Comment by 2020211993** [comment]
Hi @ShijianXu!
I've also encountered this problem. I sent the author an email a week ago but haven’t received a reply.After making some adjustments that I thought were right, the best error I can get still falls short of the 4° mentioned in the paper. Could I trouble you for some help?
